#!/usr/bin/env bash
set -e

verbose=""
name_arg=""
while [ $# -gt 0 ]; do
  case "$1" in
  --verbose)
    verbose=1
    ;;
#   --name)
#     name_arg="$2"
#     shift
#     ;;
  -h|--help)
    echo "Lists all collaborators with access to *any* repos in an organization"
    echo "USAGE"
    echo "  gh collaborators <orgname> ..."
    exit 0
    ;;
  *)
    break
    ;;
  esac
done

echo '['
comma=""
for var in "$@"
do
    echo -n $comma
    echo '{ "org" : "'$var'", "collaborators": ['
    gh api orgs/$var/repos  --jq '.[]|.collaborators_url' | sed -e 's/{.*\}//' | xargs -n 1 -I % gh api % --jq ".[]|.login" | sort -u | xargs | sed -e 's/ /", "/g' | sed -e 's/^\(.*\)$/"\1"/'
    echo ']}'
    comma=','
done
echo ']'
